users_groups:
  - name: www-data
    system: true
users:
  - name: "{{ merchantly_user }}"
    group: www-data
    auth_key: "{{ merchantly_user_auth_keys | default([]) }}"

nvm_env: user
nvm_users:
  - "{{ merchantly_user }}"
nvm_default_node_version: v8.9.4
nvm_node_versions:
  - "{{ nvm_default_node_version }}"
nvm_root: "$HOME/.nvm"
