users_groups:
  - name: www-data
    system: true
users:
  - name: "{{ merchantly_user }}"
    group: www-data
    auth_key: "{{ merchantly_user_auth_keys | default([]) }}"

rbenv:
  env: user
  version: v1.1.1
  default_ruby: 2.4.5
  rubies:
    - version: 2.4.5

rbenv_users:
  - "{{ merchantly_user }}"

nvm_env: user
nvm_users:
  - "{{ merchantly_user }}"
nvm_default_node_version: v8.9.4
nvm_node_versions:
  - "{{ nvm_default_node_version }}"
nvm_root: "$HOME/.nvm"
