users_groups:
  - name: www-data
    system: true
users:
  - name: "{{ merchantly_user }}"
    group: www-data
    auth_key: "{{ merchantly_user_auth_keys | default([]) }}"

rbenv:
  env: user
  version: v1.1.1
  default_ruby: 2.4.5
  rubies:
    - version: 2.4.5

rbenv_users:
  - "{{ merchantly_user }}"

nvm_env: user
nvm_users:
  - "{{ merchantly_user }}"
nvm_default_node_version: v8.9.4
nvm_node_versions:
  - "{{ nvm_default_node_version }}"
nvm_root: "$HOME/.nvm"

es_major_version: '5.x'
es_version: "5.6.12"
es_instance_name: "{{ ansible_hostname }}"
es_enable_xpack: false
es_plugins:
  - plugin: "http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/{{ es_version }}/elasticsearch-analysis-morphology-{{ es_version }}.zip"

postgresql_version: 10
postgresql_users:
  - name: "{{ merchantly_db_user }}"
    pass: "{{ merchantly_db_password }}"
    encrypted: no
postgresql_databases:
  - name: "{{ merchantly_db_name }}"
    owner: postgres
postgresql_user_privileges:
  - name: "{{ merchantly_db_user }}"
    db: "{{ merchantly_db_name }}"
    priv: "ALL"
postgresql_database_extensions:
  - db: "{{ merchantly_db_name }}"
    extensions:
      - btree_gin
      - hstore
      - intarray
      - pg_buffercache
      - pg_stat_statements
      - pg_trgm
      - plpgsql
      - uuid-ossp
postgresql_pg_hba_default:
  - type: local
    database: all
    user: "{{ postgresql_admin_user }}"
    address: ""
    method: "{{ postgresql_default_auth_method }}"
    comment: ""
  - type: local
    database: all
    user: all
    address: ""
    method: "{{ postgresql_default_auth_method }}"
    comment: "\"local\" is for Unix domain socket connections only"
  - type: host
    database: all
    user: all
    address: "127.0.0.1/32"
    method: "{{ postgresql_default_auth_method }}"
    comment: "IPv4 local connections:"
  - type: host
    database: all
    user: all
    address: "::1/128"
    method: "{{ postgresql_default_auth_method }}"
    comment: "IPv6 local connections:"
postgresql_max_connections: 250
postgresql_max_memory: "{{ merchantly_db_max_memory | default(ansible_memtotal_mb / 4) | int }}"
postgresql_shared_buffers: "{{ (postgresql_max_memory | int / 4 ) | int }}MB"
postgresql_work_mem: "{{ postgresql_max_memory }}kB"
postgresql_effective_cache_size: "{{ (postgresql_max_memory | int / 16 ) | int }}MB"
postgresql_min_wal_size: 1024MB
postgresql_max_wal_size: 2048MB
postgresql_wal_buffers: 16MB
postgresql_maintenance_work_mem: 128MB
postgresql_checkpoint_completion_target: 0.7
postgresql_default_statistics_target: 100

thumbor_ports: "{{ range(8881, 8881 + merchantly_thumbor_count | default(3), 1) | list }}"
thumbor_security_key: "{{ merchantly_thumbor_security_key }}"
thumbor_allowed_sources_site_name:
  - "{{ merchantly_site_name | replace('.', '\\.') }}"
  - ".+\\.{{ merchantly_site_name | replace('.', '\\.') }}"
thumbor_allowed_sources_s3: "{{ [] if merchantly_static_s3 | default('') == '' else [merchantly_static_s3 | replace('.', '\\.')] }}"
thumbor_allowed_sources: "{{ thumbor_allowed_sources_site_name + thumbor_allowed_sources_s3 }}"
