---

# Сразу смотрим, чтобы у нас не было юзера по умолчанию.
# Иначе нас поимеют за 5 минут.
- name: remove default user
  tags:
    - security
  user:
    name: ubuntu
    state: absent
    remove: yes

- name: configure locale
  tags:
    - locales
  locale_gen:
    name: "{{item}}"
  with_items:
    - "{{locales}}"

- name: Disable swap
  include: swapoff.yml
  tags: configure
  when: disable_swap
