---

# This example is stolen from
# https://github.com/drhelius/travis-ansible-demo/blob/master/.travis.yml

sudo: required

language: generic

services:
  - docker

git:
  submodules: true

env:
  - distribution: ubuntu
    version: bionic
  - distribution: ubuntu
    version: xenial

before_install:
  - 'ln -s merchantly.yml.example group_vars/merchantly.yml'

script:
  - 'sudo make test'
