---

# Example stolen from 
# https://github.com/drhelius/travis-ansible-demo/blob/master/.travis.yml

sudo: required

language: generic

services:
  - docker

git:
  submodules: true

env: 
  - distribution: ubuntu
    version: bionic
  - distribution: ubuntu
    version: trusty
  - distribution: ubuntu
    version: xenial

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'
  - 'ln -s merchantly.yml.example group_vars/merchantly.yml'
  - 'ln -s travis/hosts.ini hosts.ini'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/merchantly:rw ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook --version'
  - 'sudo docker exec "$(cat ${container_id})" /etc/ansible/roles/merchantly/travis/install'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/merchantly/main.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/merchantly/main.yml'
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/merchantly/main.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - 'sudo docker rm -f "$(cat ${container_id})"'
