---
- hosts: all
  roles:
    - zabbix-agent
    - bm-zabbix-agent
    - ansible-smartmontools
    - core
    - common
    - os-hardening
    - vim
    - hostname
    - timezone
    - ntp
    - iptables
    - logrotate
    - git

  # must be yes for zabbix-agent
  gather_facts: yes
  become: yes
