---

# https://github.com/v-zhuravlev/zbx-smartctl
#
- hosts: all
  roles:
    - zabbix-agent
    - bm-zabbix-agent
    - ansible-smartmontools

  # must be yes for zabbix-agent
  gather_facts: yes
  become: yes
