---

# https://github.com/v-zhuravlev/zbx-smartctl
#
- hosts: all
  roles:
    - zabbix-agent
    - bm-zabbix-agent
    - ansible-smartmontools

  # must be yes for zabbix-agent
  gather_facts: yes
  become: yes
  vars:
    __smartd_email: "servers@kiiiosk.ru"
    zabbix_common_config_minor_version: '3.2'
    zabbix_agent_config_server: '94.232.57.6,136.243.75.79,127.0.0.1,148.251.195.87'
    zabbix_agent_config_server_active: '94.232.57.6'
    zabbix_agent_config_include_confs: ["process", "sockstat", "diskstats", "meminfo", "psql", "nginx", "memcached", "postfix", "redis", "sidekiq", "smartctl", "uhdd"]

    zabbix_agent_pkg_state: latest
    zabbix_common_apt_repository: "deb http://repo.zabbix.com/zabbix/{{ zabbix_common_config_minor_version }}/{{ ansible_distribution|lower }} xenial main contrib non-free"
