# vim:ft=ansible:
---
- hosts: all
  tasks:
    - name: Synchronize nginx configs
      synchronize:
        src: files/nginx
        dest: /etc

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
