---
- hosts: all
  roles:
    - vim
    - hostname
    - timezone
    - ntp
    - zabbix-agent
    - cron
    - iptables
    - common
    - os-hardening
    - logrotate
    - git

  # must be yes for zabbix-agent
  gather_facts: yes
  become: yes

- hosts: databases
  roles:
    - postgresql
    - elasticsearch

# TODO
# write content CONF_DIR=/etc/elasticsearch/node1/ into /etc/default/elasticsearch
