---
- hosts: all
  roles:
    - ANXS.hostname
    - Stouts.timezone
    - ntp
    - flaminem.zabbix-agent
    - franklinkim.cron
    - Stouts.iptables
    - common

  # must be yes for zabbix-agent
  gather_facts: yes

  become: yes

- hosts: databases
  roles:
    - ANXS.postgresql
    - { role: ansible-elasticsearch, es_instance_name: "node1" }

  # write content CONF_DIR=/etc/elasticsearch/node1/ into /etc/default/elasticsearch
