---
- hosts: all-fake
  roles:
    - core
    - common
    - os-hardening
    - vim
    - hostname
    - timezone
    - ntp
    - zabbix-agent
    - bm-zabbix-agent
    - cron
    - iptables
    - logrotate
    - git

  # must be yes for zabbix-agent
  gather_facts: yes
  become: yes

- include: databases.yml
