---
- hosts: all-fake
  roles:
    - core
    - common
    - os-hardening
    - vim
    - hostname
    - timezone
    - ntp
    - cron
    - iptables
    - logrotate
    - git

  become: yes

- include: zabbix.yml
- include: databases.yml
