---
- hosts: all
  roles:
    - ANXS.hostname
    - Stouts.timezone
    - ntp

  # must be yes for zabbix-agent
  gather_facts: yes
  vars:
    timezone_enabled: yes 
    timezone_timezone: Europe/Moscow
#  tasks:
#    - raw: which python || apt-get update
#      tags: install_python
#    - raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude
#      tags: install_python
- hosts: db
  roles:
    - ANXS.postgresql
    - { role: ansible-elasticsearch, es_instance_name: "node1" }
  become: yes

  vars:
    postgresql_user: wwwkiiiosk
    postgresql_database: kiosk_production
    postgresql_version: 9.6
    postgresql_encoding: 'UTF-8'
    postgresql_locale: 'en_US.UTF-8'
    postgresql_ctype: 'en_US.UTF-8'

    postgresql_admin_user: "postgres"
    postgresql_default_auth_method: "trust"

    postgresql_service_enabled: false # should the service be enabled, default is true

    postgresql_pg_hba_passwd_hosts:
      - { type: local, database: '{{ postgresql_database }}', user: '{{ postgresql_user }}', address: '136.243.75.105/32', method: 'md5', comment: 'srv-1.kiiiosk.ru' }

    postgresql_user_privileges:
      - name: '{{ postgresql_user }}'
        db: '{{ postgresql_database }}'
        priv: "ALL"
