---

- src: https://github.com/resmo/ansible-role-zabbix-agent.git
  version: v1.1.0
  name: zabbix-agent

- src: https://github.com/resmo/ansible-role-ntp.git
  version: 0.4.0
  name: ntp

- src: https://github.com/Stouts/Stouts.timezone.git
  version: 2.2.0
  name: Stouts.timezone

- src: https://github.com/ANXS/postgresql.git
  version: v1.9.0
  name: ANXS.postgresql

- src: https://github.com/ANXS/hostname.git
  version: v1.1.0
  name: ANXS.hostname

- src: https://github.com/elastic/ansible-elasticsearch.git
  version: 5.5.1
  name: ansible-elasticsearch

- src: https://github.com/ANXS/vim.git
  version: v1.0.2
  name: ANXS-bim
