---
- src: https://github.com/CyVerse-Ansible/ansible-geoip.git
  name: geoip

- src: https://github.com/geerlingguy/ansible-role-redis.git
  name: redis

- src: https://github.com/zzet/ansible-rbenv-role.git
  name: rbenv

- src: https://github.com/BrandyMint/ansible-zabbix-agent.git
  name: bm-zabbix-agent

- src: https://github.com/tepez/ansible-role-nvm.git
  name: nvm

- src: https://github.com/Oefenweb/ansible-yarn.git
  name: yarn

- src: https://github.com/grimmjow8/ansible-smartmontools.git
  name: ansible-smartmontools

- src: https://github.com/debops/ansible-core.git
  name: core

- src: https://github.com/geerlingguy/ansible-role-git.git
  name: git
  version: 1.4.0

- src: https://github.com/nickhammond/ansible-logrotate.git
  name: logrotate
  version: v0.0.3

- src: https://github.com/dev-sec/ansible-os-hardening.git
  name: os-hardening

- src: https://github.com/Stouts/Stouts.iptables.git
  version: 1.1.3
  name: iptables

- src: https://github.com/flaminem/ansible-role-zabbix-agent.git
  version: 9967f7ac7ed4fddfc8d7fc15aa70febbc0ea8aae
  name: zabbix-agent

- src: https://github.com/brandymint/ansible-role-zabbix-common.git
  name: zabbix-common

- src: https://github.com/resmo/ansible-role-ntp.git
  version: 0.4.0
  name: ntp

- src: https://github.com/Stouts/Stouts.timezone.git
  version: 2.2.0
  name: timezone

- src: https://github.com/ANXS/postgresql.git
  version: v1.9.0
  name: postgresql

- src: https://github.com/ANXS/hostname.git
  version: v1.1.0
  name: hostname

# ansible-galaxy install elastic.elasticsearch
- src: https://github.com/elastic/ansible-elasticsearch.git
  name: elasticsearch

- src: https://github.com/ANXS/vim.git
  version: v1.0.2
  name: vim
