# vim:ft=ansible:
---
- hosts: all
  pre_tasks:
    - name: Install thumbor dependencies
      apt: name={{item}} state=installed
      with_items:
        - gifsicle
        - ffmpeg
        - libjpeg-dev
        - libpng-dev
        - libtiff-dev
        - libgtk2.0-dev
        - python-numpy
        - python-pycurl
        - webp
        - python-opencv
        - python-dev
        - python-pip
    - name: Install pip thumbor
      pip:
        name: thumbor

    - name: Synchronize configs
      synchronize:
        src: files/thumbor/etc
        dest: /

    - name: install pip thumbor_text_filter
      pip: name=thumbor_text_filter

    - name: Start systemd thumbor services
      systemd: state=started name={{item}} enabled=True
      with_items:
        - thumbor-1
        - thumbor-2
        - thumbor-3
