# This task disables swap for Kubernetes node (see https://github.com/kubernetes/kubernetes/pull/31996)
- name: Manage swap file in /etc/fstab
  mount:
    name: 'none'
    fstype: 'swap'
    opts: 'sw,nofail'
    dump: '0'
    passno: '0'
    state: 'absent'
  when: disable_swap
    # state: '{{ "absent" if disable_swap else "present" }}'

  #- name: Remove swapfile from /etc/fstab
  #mount:
    #name: swap
    #fstype: swap
    #state: absent

- name: Disable swap
  command: swapoff -a
  when: disable_swap and ansible_swaptotal_mb > 0

- name: set vm.swappiness
  when: disable_swap
  sysctl:
    name: vm.swappiness
    value: 0
    sysctl_set: yes
    state: present
    reload: yes
