- name: ensure direnv is installed
  apt:
    name: direnv

- name: ensure direnv profile hook is installed
  copy:
    content: 'eval "$(direnv hook bash)"'
    dest: /etc/profile.d/direnv.sh
    owner: root
    group: root
    mode: 0644
