---
- name: install zabbix agent for Debian OS family
  apt: pkg=zabbix-agent state={{ zabbix_agent_pkg_state }}
  when: ansible_os_family == 'Debian'
  tags: ["packages","zabbix-agent","zabbix"]

- name: install zabbix agent for RedHat OS family
  yum: name=zabbix-agent state={{ zabbix_agent_pkg_state }}
  when: ansible_os_family == 'RedHat'
  tags: ["packages","zabbix-agent","zabbix"]

- name: Ensure log folder exist
  file: path=/var/log/zabbix state=directory owner="{{zabbix_agent_user}}" group="{{zabbix_agent_group}}" mode=700 
  notify: restart zabbix-agent
  tags: ["configuration","zabbix-agent","zabbix"]

- name: configure zabbix agent
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent
  tags: ["configuration","zabbix-agent","zabbix"]

- name: create zabbix agent optional config directory
  file: path={{ zabbix_agent_config_include }} state=directory
  tags: ["configuration","zabbix-agent","zabbix"]

- name: copy additional configs
  copy: src={{ item }}.conf dest={{ zabbix_agent_config_include }}/{{ item }}.conf
  with_items: '{{ zabbix_agent_config_include_confs }}'
  notify: restart zabbix-agent
  tags: ["configuration","zabbix-agent","zabbix"]

- name: ensure zabbix agent started/stopped
  service: name=zabbix-agent state={{ zabbix_agent_service_state }} enabled={{ zabbix_agent_service_enabled }} pattern="/zabbix_agentd"
  tags: ["configuration","service","zabbix-agent","zabbix"]

