galaxy_info:
  author: Ryan Brown
  description: Ansible role installs smartmontools and configures smartd.
  license: MIT
  min_ansible_version: 2.1.2.0
  
  platforms:
   - name: Ubuntu
     versions:
      - trusty

   - name: Debian
     versions:
      - jessie

  galaxy_tags:
   - system

dependencies: []
