---
- name: Check for current node version
  shell: ". {{ nvm.path}}/nvm.sh &&  nvm use {{ nvm.default_node_version }} > /dev/null 2>&1 && node -v"
  register: nvm_node_version
  ignore_errors: yes
  changed_when: false

- name: Install node
  command: ". {{ nvm.path}}/nvm.sh && nvm install {{ nvm.default_node_version }}"
  when: nvm_node_version.stdout.find(nvm.node_version) == -1

- name: Set default node version to installed node
  command: ". {{ nvm.path }}/nvm.sh && nvm alias default {{ nvm.node_version }}"
  when: nvm_node_version.stdout.find(nvm.node_version) == -1
